# NETWORK
listen_addresses = '*'
max_connections = 100

# REPLICATION (CDC)
wal_level = logical
max_replication_slots = 10
max_wal_senders = 10

# RESOURCES
shared_buffers = 256MB
work_mem = 4MB

# WAL
max_wal_size = 1GB
min_wal_size = 80MB

# include 'custom_prod.conf'    # Позволяет подключать доп. настройки для прода
